services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
  environment:
    APP_DEBUG: "true"
    APP_HOST: "0.0.0.0"
    APP_PORT: "8000"
    VITE_HOST: "127.0.0.1"
    DB_NAME: "water_monitor"
    DB_PORT: "3306"
    DB_HOST: mysql
    DB_USER: "root"
    DB_PASS: ""
    BOT_TOKEN: ""
    BOT_USERNAME: "esp_water12_bot"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: